In [1]:
import pandas as pd

In [2]:
file1 = "Demographic Data/demographic_details.csv"
file2 = "../Resources/acc_intake_outcome.csv"
demographics = pd.read_csv(file1)
shelter = pd.read_csv(file2)

In [3]:
# Drop columns in demographics DF
demographics.drop(["land_area_in_sqmi", "population_by_age", "school_enrollment_age_3_to_17"], axis = 1, inplace= True)
demographics = demographics.loc[:, ~demographics.columns.str.contains('^Unnamed')]

demographics.head(3)

,zipcode,major_city,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over
0,78724,Austin,Travis County,TX,21696,889.0,6138,38479,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
1,78660,Pflugerville,Travis County,TX,68789,1519.0,23950,76007,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
2,78747,Austin,Travis County,TX,14808,623.0,5491,61599,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."

In [4]:
#Rename zipcode_intake to zipcode df.rename(columns={"A": "a", "B": "c"})

shelter.rename(columns = {"zipcode_intake":"zipcode"}, inplace = True)

In [5]:
# Drop rows without zip codes
shelter = shelter.dropna(axis=0, subset=['zipcode'])

In [6]:
# Merge two DF 

animal_demo_df = shelter.merge(demographics, on= "zipcode")
animal_demo_df.head()

,index_id_intake,animal_id_intake,datetime_intake,monthyear_intake,found_location,intake_type,intake_condition,animal_type_intake,sex_upon_intake,age_upon_intake,...,major_city,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over
0,69127,A293383,2018-03-18 18:17:00,March 2018,6005 Walnut Hills in Austin (TX),Stray,Sick,Cat,Neutered Male,15 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
1,74120,A598657,2017-12-10 10:20:00,December 2017,2938 Pecan Springs Rd in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
2,15329,A670563,2014-01-10 11:35:00,January 2014,5209 Cameron Rd in Austin (TX),Stray,Normal,Dog,Intact Female,1 year,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
3,47825,A674455,2014-03-13 12:22:00,March 2014,6403 Chimney Creek in Austin (TX),Owner Surrender,Normal,Dog,Spayed Female,3 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
4,46463,A679232,2014-05-17 16:23:00,May 2014,7227 E Hwy 290 in Austin (TX),Stray,Normal,Cat,Neutered Male,4 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."

In [7]:
#cust_sell = mainDf[mainDf.Type == 'S']

cat_demo = animal_demo_df[animal_demo_df.animal_type_intake == "Cat"]
cat_demo.head()

,index_id_intake,animal_id_intake,datetime_intake,monthyear_intake,found_location,intake_type,intake_condition,animal_type_intake,sex_upon_intake,age_upon_intake,...,major_city,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over
0,69127,A293383,2018-03-18 18:17:00,March 2018,6005 Walnut Hills in Austin (TX),Stray,Sick,Cat,Neutered Male,15 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
4,46463,A679232,2014-05-17 16:23:00,May 2014,7227 E Hwy 290 in Austin (TX),Stray,Normal,Cat,Neutered Male,4 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
6,77871,A691706,2014-11-08 12:28:00,November 2014,5609 Gloucester in Austin (TX),Stray,Normal,Cat,Intact Female,1 month,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
8,10373,A701506,2015-04-30 13:44:00,April 2015,1416 Braes Ridge in Austin (TX),Stray,Sick,Cat,Spayed Female,10 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
9,64986,A701636,2015-05-02 14:42:00,May 2015,1703 Cloverleaf Drive in Austin (TX),Stray,Normal,Cat,Unknown,1 week,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."

In [8]:
dog_demo = animal_demo_df[animal_demo_df.animal_type_intake == "Dog"]
dog_demo.head()

,index_id_intake,animal_id_intake,datetime_intake,monthyear_intake,found_location,intake_type,intake_condition,animal_type_intake,sex_upon_intake,age_upon_intake,...,major_city,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over
1,74120,A598657,2017-12-10 10:20:00,December 2017,2938 Pecan Springs Rd in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
2,15329,A670563,2014-01-10 11:35:00,January 2014,5209 Cameron Rd in Austin (TX),Stray,Normal,Dog,Intact Female,1 year,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
3,47825,A674455,2014-03-13 12:22:00,March 2014,6403 Chimney Creek in Austin (TX),Owner Surrender,Normal,Dog,Spayed Female,3 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
5,134557,A687529,2014-09-06 03:27:00,September 2014,1809 Rogge in Austin (TX),Public Assist,Normal,Dog,Spayed Female,2 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
7,18642,A692256,2014-11-17 15:13:00,November 2014,4902 Russet Hill in Austin (TX),Stray,Injured,Dog,Intact Male,3 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."

In [9]:
dog_demo.to_csv("../Resources/dog_demo.csv")
cat_demo.to_csv("../Resources/cat_demo.csv")