In [1]:
import pandas as pd

In [2]:
file = "../Resources/all_animals_demographics.csv"
demo_df = pd.read_csv(file)
demo_df.head(3)

,Unnamed: 0,index_id_intake,animal_id_intake,datetime_intake,monthyear_intake,found_location,intake_type,intake_condition,animal_type_intake,sex_upon_intake,...,major_city,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over
0,0,69127,A293383,2018-03-18 18:17:00,March 2018,6005 Walnut Hills in Austin (TX),Stray,Sick,Cat,Neutered Male,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
1,1,74120,A598657,2017-12-10 10:20:00,December 2017,2938 Pecan Springs Rd in Austin (TX),Stray,Normal,Dog,Spayed Female,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
2,2,15329,A670563,2014-01-10 11:35:00,January 2014,5209 Cameron Rd in Austin (TX),Stray,Normal,Dog,Intact Female,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."

In [4]:
# Change index to index_id
demo_df = demo_df.set_index("index_id_intake")
demo_df.head(3)

,Unnamed: 0,animal_id_intake,datetime_intake,monthyear_intake,found_location,intake_type,intake_condition,animal_type_intake,sex_upon_intake,age_upon_intake,...,major_city,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over
index_id_intake,,,,,,,,,,,,,,,,,,,,,
69127,0,A293383,2018-03-18 18:17:00,March 2018,6005 Walnut Hills in Austin (TX),Stray,Sick,Cat,Neutered Male,15 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
74120,1,A598657,2017-12-10 10:20:00,December 2017,2938 Pecan Springs Rd in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."
15329,2,A670563,2014-01-10 11:35:00,January 2014,5209 Cameron Rd in Austin (TX),Stray,Normal,Dog,Intact Female,1 year,...,Austin,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H..."

In [5]:
demo_df = demo_df.loc[:, ~demo_df.columns.str.contains('^Unnamed')]

In [10]:
demo_df.dtypes

animal_id_intake                                      object
datetime_intake                                       object
monthyear_intake                                      object
found_location                                        object
intake_type                                           object
intake_condition                                      object
animal_type_intake                                    object
sex_upon_intake                                       object
age_upon_intake                                       object
breed_intake                                          object
color_intake                                          object
age_upon_intake(days)                                  int64
age_upon_intake(years)                               float64
age_range_intake                                      object
intake_month                                           int64
intake_year                                            int64
intake_weekday                                        object
intake_hour                                            int64
intake_frequency                                       int64
order_of_intake                                        int64
index_id_outcome                                       int64
animal_id_outcome                                     object
datetime_outcome                                      object
monthyear_outcome                                     object
date_of_birth_outcome                                 object
outcome_type                                          object
outcome_subtype                                       object
animal_type_outcome                                   object
sex_upon_outcome                                      object
age_upon_outcome                                      object
breed_outcome                                         object
color_outcome                                         object
age_upon_outcome(days)                                 int64
outcome_month                                          int64
outcome_year                                           int64
outcome_weekday                                       object
outcome_hour                                           int64
age_upon_outcome(years)                              float64
age_range_outcome                                     object
outcome_frequency                                      int64
order_of_outcome                                       int64
breed_intake_subtype                                  object
main_breed_intake                                     object
breed_contains_pitbull                                object
sex_upon_intake_subtype                               object
time_in_shelter                                       object
days_in_shelter                                        int64
zipcode                                              float64
longitude_intake                                      object
latitude_intake                                      float64
major_city                                            object
county                                                object
state                                                 object
population                                             int64
population_density                                   float64
housing_units                                          int64
median_household_income                                int64
population_by_gender                                  object
population_by_race                                    object
educational_attainment_for_population_25_and_over     object
dtype: object

In [13]:
demo_df["population_by_gender"].apply(pd.Series)
demo_df = pd.concat([demo_df, demo_df["population_by_gender"].apply(pd.Series)],axis =1)
demo_df.head()

,animal_id_intake,datetime_intake,monthyear_intake,found_location,intake_type,intake_condition,animal_type_intake,sex_upon_intake,age_upon_intake,breed_intake,...,county,state,population,population_density,housing_units,median_household_income,population_by_gender,population_by_race,educational_attainment_for_population_25_and_over,0
index_id_intake,,,,,,,,,,,,,,,,,,,,,
69127,A293383,2018-03-18 18:17:00,March 2018,6005 Walnut Hills in Austin (TX),Stray,Sick,Cat,Neutered Male,15 years,Siamese,...,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H...","[{'key': 'Data', 'values': [{'x': 'Male', 'y':..."
74120,A598657,2017-12-10 10:20:00,December 2017,2938 Pecan Springs Rd in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,Pit Bull,...,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H...","[{'key': 'Data', 'values': [{'x': 'Male', 'y':..."
15329,A670563,2014-01-10 11:35:00,January 2014,5209 Cameron Rd in Austin (TX),Stray,Normal,Dog,Intact Female,1 year,Pit Bull Mix,...,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H...","[{'key': 'Data', 'values': [{'x': 'Male', 'y':..."
47825,A674455,2014-03-13 12:22:00,March 2014,6403 Chimney Creek in Austin (TX),Owner Surrender,Normal,Dog,Spayed Female,3 years,Australian Cattle Dog/Labrador Retriever,...,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H...","[{'key': 'Data', 'values': [{'x': 'Male', 'y':..."
46463,A679232,2014-05-17 16:23:00,May 2014,7227 E Hwy 290 in Austin (TX),Stray,Normal,Cat,Neutered Male,4 years,Domestic Shorthair Mix,...,Travis County,TX,28330,4083.0,12398,42939,"[{'key': 'Data', 'values': [{'x': 'Male', 'y':...","[{'key': 'Data', 'values': [{'x': 'White', 'y'...","[{'key': 'Data', 'values': [{'x': 'Less Than H...","[{'key': 'Data', 'values': [{'x': 'Male', 'y':..."

In [24]:
demo_df.dtypes

animal_id_intake                                     object
datetime_intake                                      object
monthyear_intake                                     object
found_location                                       object
intake_type                                          object
                                                      ...
median_household_income                               int64
population_by_gender                                 object
population_by_race                                   object
educational_attainment_for_population_25_and_over    object
0                                                    object
Length: 61, dtype: object

In [18]:
Population_by_gender = demo_df['population_by_gender']
Population_by_gender.head()

index_id_intake
69127    [{'key': 'Data', 'values': [{'x': 'Male', 'y':...
74120    [{'key': 'Data', 'values': [{'x': 'Male', 'y':...
15329    [{'key': 'Data', 'values': [{'x': 'Male', 'y':...
47825    [{'key': 'Data', 'values': [{'x': 'Male', 'y':...
46463    [{'key': 'Data', 'values': [{'x': 'Male', 'y':...
Name: population_by_gender, dtype: object

In [27]:
Population_by_gender.str.replace(r''key': 'Data', 'values':'')
Population_by_gender.head()

SyntaxError: invalid syntax (Temp/ipykernel_24136/1764159859.py, line 1)