In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('../../../../Data Files/AAC_Intake_etl.csv')
df.head(5)

,Index_ID,Animal_ID,DateTime,MonthYear,Found_Location,Intake_Type,Intake_Condition,Animal_Type,Sex_upon_Intake,Age_upon_Intake,...,Color,Age_Upon_Intake(days),Age_Upon_Intake(years),Age_Range,Intake_Month,Intake_Year,Intake_Weekday,Intake_Hour,Intake_Frequency,Order_of_Intake
0,99104,A006100,3/7/2014 14:26,Mar-14,8700 Research in Austin (TX),Public Assist,Normal,Dog,Neutered Male,6 years,...,Yellow/White,2190,6.0,"(5.0, 7.5]",3,2014,Friday,14,3,1
1,4716,A006100,12/19/2014 10:21,Dec-14,8700 Research Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,7 years,...,Yellow/White,2555,7.0,"(5.0, 7.5]",12,2014,Friday,10,3,2
2,21962,A006100,12/7/2017 14:07,Dec-17,Colony Creek And Hunters Trace in Austin (TX),Stray,Normal,Dog,Neutered Male,10 years,...,Yellow/White,3650,10.0,"(7.5, 10.0]",12,2017,Thursday,14,3,3
3,77010,A047759,4/2/2014 15:55,Apr-14,Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,10 years,...,Tricolor,3650,10.0,"(7.5, 10.0]",4,2014,Wednesday,15,1,1
4,104793,A134067,11/16/2013 9:02,Nov-13,12034 Research Blvd in Austin (TX),Public Assist,Injured,Dog,Neutered Male,16 years,...,Brown/White,5840,16.0,"(15.0, 17.5]",11,2013,Saturday,9,1,1

In [6]:
location_df = df[['Index_ID','Animal_ID','Found_Location']]
location_df.head(5)

   Index_ID Animal_ID                                 Found_Location
0     99104   A006100                   8700 Research in Austin (TX)
1      4716   A006100              8700 Research Blvd in Austin (TX)
2     21962   A006100  Colony Creek And Hunters Trace in Austin (TX)
3     77010   A047759                                    Austin (TX)
4    104793   A134067             12034 Research Blvd in Austin (TX)

In [7]:
location_df['Found_Location_count'] = location_df['Found_Location'].str.count(' ') + 1

/var/folders/3m/mj278b89297553km9_g94ghr0000gn/T/ipykernel_7833/3253314857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df['Found_Location_count'] = location_df['Found_Location'].str.count(' ') + 1

In [383]:
#location_df=location_df.drop('Found_Location1',axis=1)

In [8]:
short_named_citites = location_df[location_df['Found_Location_count'].isin([2,3])]
short_named_citites.Found_Location.unique()

array(['Austin (TX)', 'Travis (TX)', 'Del Valle (TX)',
       'Outside Jurisdiction', 'Manor (TX)', 'Pflugerville (TX)',
       'Williamson (TX)', 'Lago Vista (TX)', 'Lakeway (TX)',
       'Cedar Park (TX)', 'Hays (TX)', 'Round Rock (TX)',
       'Jonestown (TX)', 'Leander (TX)', 'Bastrop (TX)', 'Bee Cave (TX)',
       'Creedmoor (TX)', 'Burnet (TX)', 'Point Venture (TX)',
       'Mustang Ridge (TX)', 'Caldwell (TX)', 'Webberville (TX)'],
      dtype=object)

In [9]:
short_cities_list = ['Austin (TX)', 'Travis (TX)', 'Del Valle (TX)',
       'Outside Jurisdiction', 'Manor (TX)', 'Pflugerville (TX)',
       'Williamson (TX)', 'Lago Vista (TX)', 'Lakeway (TX)',
       'Cedar Park (TX)', 'Hays (TX)', 'Round Rock (TX)',
       'Jonestown (TX)', 'Leander (TX)', 'Bastrop (TX)', 'Bee Cave (TX)',
       'Creedmoor (TX)', 'Burnet (TX)', 'Point Venture (TX)',
       'Mustang Ridge (TX)', 'Caldwell (TX)', 'Webberville (TX)']

In [10]:
# Eliminating cities with 2 letter words as in two_word_cities since they do not give us the right addresses.
# Reduces to 105224

refined_locations = location_df[~location_df['Found_Location'].isin(short_cities_list)]
refined_locations

,Index_ID,Animal_ID,Found_Location,Found_Location_count
0,99104,A006100,8700 Research in Austin (TX),5
1,4716,A006100,8700 Research Blvd in Austin (TX),6
2,21962,A006100,Colony Creek And Hunters Trace in Austin (TX),8
4,104793,A134067,12034 Research Blvd in Austin (TX),6
6,138992,A163459,Ih 35 And 41St St in Austin (TX),8
...,...,...,...,...
138292,143822,A864885,806 Sirocco Drive in Austin (TX),6
138293,143832,A864886,6607 S Us 183 Highway in Travis (TX),8
138294,143837,A864887,6607 S Us 183 Highway in Travis (TX),8
138295,143828,A864898,9805 Briar Ridge Road in Austin (TX),7
138296,143830,A864900,Airport And Bolm in Austin (TX),6

In [11]:
uniqueId = refined_locations["Animal_ID"].unique() 
uniqueId

array(['A006100', 'A134067', 'A163459', ..., 'A864887', 'A864898',
       'A864900'], dtype=object)

In [12]:
refined_locations= refined_locations.drop_duplicates(subset=['Animal_ID'],keep=False)
refined_locations

,Index_ID,Animal_ID,Found_Location,Found_Location_count
4,104793,A134067,12034 Research Blvd in Austin (TX),6
6,138992,A163459,Ih 35 And 41St St in Austin (TX),8
7,18434,A165752,Gatlin Gun Rd And Brodie in Austin (TX),8
8,94130,A169438,Dessau in Austin (TX),4
10,47828,A189592,Chesney And Slaughter in Austin (TX),6
...,...,...,...,...
138292,143822,A864885,806 Sirocco Drive in Austin (TX),6
138293,143832,A864886,6607 S Us 183 Highway in Travis (TX),8
138294,143837,A864887,6607 S Us 183 Highway in Travis (TX),8
138295,143828,A864898,9805 Briar Ridge Road in Austin (TX),7
138296,143830,A864900,Airport And Bolm in Austin (TX),6

In [13]:
address_start_digit = refined_locations.Found_Location.str[0].str.isdigit()
address_start_digit

4          True
6         False
7         False
8         False
10        False
          ...
138292     True
138293     True
138294     True
138295     True
138296    False
Name: Found_Location, Length: 93542, dtype: bool

In [390]:
refined_locations = refined_locations.loc[address_start_digit]
refined_locations

,Index_ID,Animal_ID,Found_Location,Found_Location_count
4,104793,A134067,12034 Research Blvd in Austin (TX),6
11,118068,A191351,1912 E William Cannon Rd in Austin (TX),8
12,60050,A197810,4616 E Cesar Chavez in Austin (TX),7
15,90293,A210457,4424 S Mopac #412 in Austin (TX),7
16,13564,A212672,14611 Wells Port Dr in Austin (TX),8
...,...,...,...,...
138291,143813,A864884,1500 E Parmer Lane in Austin (TX),7
138292,143822,A864885,806 Sirocco Drive in Austin (TX),6
138293,143832,A864886,6607 S Us 183 Highway in Travis (TX),8
138294,143837,A864887,6607 S Us 183 Highway in Travis (TX),8
138295,143828,A864898,9805 Briar Ridge Road in Austin (TX),7

In [14]:
# # unique_list = refined_locations.Found_Location.unique().tolist()
# refined_locations.Found_Location.unique().tolist()
# unique_df = refined_locations[refined_locations['Found_Location'].isin(refined_locations.Found_Location.unique().tolist())]
# unique_df


refined_locations.Found_Location.nunique()

50395

In [23]:
refined_locations["State"] = refined_locations["Found_Location"].str.split().str[-1]

/var/folders/3m/mj278b89297553km9_g94ghr0000gn/T/ipykernel_7833/3199055635.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refined_locations["State"] = refined_locations["Found_Location"].str.split().str[-1]

In [24]:
refined_locations["City"] = refined_locations["Found_Location"].str.split().str[-2]

/var/folders/3m/mj278b89297553km9_g94ghr0000gn/T/ipykernel_7833/4073325088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refined_locations["City"] = refined_locations["Found_Location"].str.split().str[-2]

In [25]:

refined_locations['Address'] = refined_locations["Found_Location"].apply(lambda s: ', '.join([' '.join(x.split()[:-2]) for x in s.split(',')]))
refined_locations

/var/folders/3m/mj278b89297553km9_g94ghr0000gn/T/ipykernel_7833/340835155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refined_locations['Address'] = refined_locations["Found_Location"].apply(lambda s: ', '.join([' '.join(x.split()[:-2]) for x in s.split(',')]))

,Index_ID,Animal_ID,Found_Location,Found_Location_count,State,City,Address
4,104793,A134067,12034 Research Blvd in Austin (TX),6,(TX),Austin,12034 Research Blvd in
6,138992,A163459,Ih 35 And 41St St in Austin (TX),8,(TX),Austin,Ih 35 And 41St St in
7,18434,A165752,Gatlin Gun Rd And Brodie in Austin (TX),8,(TX),Austin,Gatlin Gun Rd And Brodie in
8,94130,A169438,Dessau in Austin (TX),4,(TX),Austin,Dessau in
10,47828,A189592,Chesney And Slaughter in Austin (TX),6,(TX),Austin,Chesney And Slaughter in
...,...,...,...,...,...,...,...
138292,143822,A864885,806 Sirocco Drive in Austin (TX),6,(TX),Austin,806 Sirocco Drive in
138293,143832,A864886,6607 S Us 183 Highway in Travis (TX),8,(TX),Travis,6607 S Us 183 Highway in
138294,143837,A864887,6607 S Us 183 Highway in Travis (TX),8,(TX),Travis,6607 S Us 183 Highway in
138295,143828,A864898,9805 Briar Ridge Road in Austin (TX),7,(TX),Austin,9805 Briar Ridge Road in
138296,143830,A864900,Airport And Bolm in Austin (TX),6,(TX),Austin,Airport And Bolm in

In [26]:
refined_locations = refined_locations.drop_duplicates(subset=["Found_Location"],keep="first")
refined_locations

,Index_ID,Animal_ID,Found_Location,Found_Location_count,State,City,Address
4,104793,A134067,12034 Research Blvd in Austin (TX),6,(TX),Austin,12034 Research Blvd in
6,138992,A163459,Ih 35 And 41St St in Austin (TX),8,(TX),Austin,Ih 35 And 41St St in
7,18434,A165752,Gatlin Gun Rd And Brodie in Austin (TX),8,(TX),Austin,Gatlin Gun Rd And Brodie in
8,94130,A169438,Dessau in Austin (TX),4,(TX),Austin,Dessau in
10,47828,A189592,Chesney And Slaughter in Austin (TX),6,(TX),Austin,Chesney And Slaughter in
...,...,...,...,...,...,...,...
138288,143796,A864875,3707 Menchaca Rd in Austin (TX),6,(TX),Austin,3707 Menchaca Rd in
138291,143813,A864884,1500 E Parmer Lane in Austin (TX),7,(TX),Austin,1500 E Parmer Lane in
138292,143822,A864885,806 Sirocco Drive in Austin (TX),6,(TX),Austin,806 Sirocco Drive in
138293,143832,A864886,6607 S Us 183 Highway in Travis (TX),8,(TX),Travis,6607 S Us 183 Highway in
138295,143828,A864898,9805 Briar Ridge Road in Austin (TX),7,(TX),Austin,9805 Briar Ridge Road in

In [27]:
refined_locations.head()

,Index_ID,Animal_ID,Found_Location,Found_Location_count,State,City,Address
4,104793,A134067,12034 Research Blvd in Austin (TX),6,(TX),Austin,12034 Research Blvd in
6,138992,A163459,Ih 35 And 41St St in Austin (TX),8,(TX),Austin,Ih 35 And 41St St in
7,18434,A165752,Gatlin Gun Rd And Brodie in Austin (TX),8,(TX),Austin,Gatlin Gun Rd And Brodie in
8,94130,A169438,Dessau in Austin (TX),4,(TX),Austin,Dessau in
10,47828,A189592,Chesney And Slaughter in Austin (TX),6,(TX),Austin,Chesney And Slaughter in

In [ ]:
#unique_df.to_csv('unique_csv',encoding='utf-8')

In [28]:
refined_locations.to_csv('data_refined.csv',encoding='utf-8')